import fs from "fs";
import path from "path";
import matter from "gray-matter";
import Head from "next/head";
import Post from "../components/Post";
import { sortByDate } from "../utils/index";

export async function getStaticProps() {
  // Get Files From The posts dir

  const files = fs.readdirSync(path.join("posts"));

  // Get Slug and frontmatter from posts

  const posts = files.map((fileName) => {
    // create slug

    const slug = fileName.replace(".md", "");

    // get Get frontMater

    const markdownWithMatter = fs.readFileSync(
      path.join("posts", fileName),
      "utf-8"
    );

    const { data: frontmatter } = matter(markdownWithMatter);

    return {
      slug,
      frontmatter,
    };
  });

  return {
    props: {
      posts: posts.sort(sortByDate),
    },
  };
}

export default function Home({ posts }) {
  console.log(posts);
  return (
    <div>
      <Head>
        <title>Dev Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="posts">
        {posts.map((post) => {
          return <Post post={post} key={post?.slug} />;
        })}
      </div>
    </div>
  );
}
